
# **Guía #2: Álgebra de Matrices**

**Objetivo:** Usar el lenguaje de programación de Python para el desarrollo y apropiación de las propiedades básicas de las matrices.

**Temas:** En esta guía se trabajarán las distintas  operaciones entre matrices como: suma, resta, multiplicación por escalar y multiplicación entre matrices; y transpuesta de una matriz.




## **Creación de matrices**

Para la creación y tratado de matrices se debe llamar la biblioteca "**numpy**". Ésta biblioteca da soporte para crear vectores y matrices, y permite la realización de las diversas operaciones entre éstos elementos. "**Numpy**" generalmente se importa con el alias "**np**". En los siguientes ejemplos se muestra cómo llamar esta biblioteca.

### **Ejemplo 1:**
Crear las siguientes matrices:



\begin{equation*}
 A =
\begin{pmatrix}
1 & 2 & 3\\
-1 & 4 & 0\\
-6 & 0 & 10
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
2 & 5 & 0\\
7 & 3 & 8\\
3 & 0 & 1
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
5 & -8 & 0\\
2 & -4 & -3 \\
-5 & 0 & 4
\end{pmatrix},
\hspace{1cm}
I =
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}.
\end{equation*}


In [1]:
# Solución del Ejemplo 1.

# Importamos la biblioteca numpy con el alias np.
import numpy as np

# Creación de las matrices A, B, C y I.

A = np.array([[1, 2, 3], [-1, 4, 0], [-6, 0, 10]])

B = np.array([[2, 5, 0], [7, 3, 8], [3, 0, 1]])

C = np.array([[5, -8, 0], [2, -4, -3], [-5, 0, 4]])

# Podemos crear la matriz identidad I como se hizo con la matrices anteriores, o simplemente usar el comando np.eye

I = np.eye(3) # matriz identidad 3 x 3

# Visualización de las matrices

A, B, C, I

(array([[ 1,  2,  3],
        [-1,  4,  0],
        [-6,  0, 10]]),
 array([[2, 5, 0],
        [7, 3, 8],
        [3, 0, 1]]),
 array([[ 5, -8,  0],
        [ 2, -4, -3],
        [-5,  0,  4]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## **Suma, resta y producto por escalar**

### **Ejemplo 2:**
Use las matrices establecidas en el Ejemplo 1 para realizar las operaciones indicadas:



a).   $(A + 5B)-(3I-2C).$

b).   $-5B + (194A - 80C) - 0.56I .$

c). $ -165(A - B + 8C - I) + \frac{4}{9}C + A     .$





In [2]:
# Solución del Ejemplo 2.

# a). Operación (A + 5B)-(3I-2C)

(A + 5*B)-(3*I-2*C)

array([[18., 11.,  3.],
       [38.,  8., 34.],
       [-1.,  0., 20.]])

In [3]:
# b). Operación -5B + (194A-80C) - 0.56I

-5*B + (194*A-80*C) - 0.56*I

array([[-216.56, 1003.  ,  582.  ],
       [-389.  , 1080.44,  200.  ],
       [-779.  ,    0.  , 1614.44]])

In [4]:
# c). Operación -165(A - B + 8C - I) + (4/9)C + A

-165*(A - B + 8*C - I) + (4/9)*C + A

array([[-6266.77777778, 11053.44444444,  -492.        ],
       [-1320.11111111,  5282.22222222,  5278.66666667],
       [ 8076.77777778,     0.        , -6588.22222222]])

## **Multiplicación entre matrices**

### **Ejemplo 3:**
Crear las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
3 & -2 & 3 & 45 & -8 & 0\\
7 & 5 & -1 & 97 & -145 & 123\\
-2 & 94 & 500 & 1 & 3 & 7 \\
8 & 2 & 8 & 1 & 2 & -12 \\
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
22 & 25 & 0 & 6\\
-7 & 2 & 56 & -10\\
3 & 0 & 1 & 87
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
-5 & 8 & 0 & 1\\
-2 & 4 & 3 & 2\\
5 & 0 & -4 & 0 \\
-5 & 0 & 4 & 3
\end{pmatrix},
\hspace{1cm}
I =
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}.
\end{equation*}


y realizar las operaciones indicadas:


a).   $7BA.$

b).   $IA.$

c). $IC-CI.$

d). $(40C + 20I)A - 9A$



In [5]:
# Solución del Ejemplo 3.

# Creación de las matrices A, B, C y I.

A = np.array([[3, -2, 3, 45, -8, 0], [7, 5, -1, 97, -145, 123], [-2, 94, 500, 1, 3, 7],[8, 2, 8, 1, 2, -12]])

B = np.array([[22, 25, 0, 6], [-7, 2, 56, -10], [3, 0, 1, 87]])

C = np.array([[-5, 8, 0, 1], [-2, 4, 3, 2], [5, 0, -4, 0],[-5, 0, 4, 3]])

# Podemos crear la matriz identidad I como se hizo con la matrices anteriores, o simplemente usar el comando np.eye

I = np.eye(4) # matriz identidad 4 x 4

# Visualización de las matrices

A, B, C, I

(array([[   3,   -2,    3,   45,   -8,    0],
        [   7,    5,   -1,   97, -145,  123],
        [  -2,   94,  500,    1,    3,    7],
        [   8,    2,    8,    1,    2,  -12]]),
 array([[ 22,  25,   0,   6],
        [ -7,   2,  56, -10],
        [  3,   0,   1,  87]]),
 array([[-5,  8,  0,  1],
        [-2,  4,  3,  2],
        [ 5,  0, -4,  0],
        [-5,  0,  4,  3]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [6]:
# a). Operación 7BA

# Nota: El producto entre matrices se ejecuta con el comando @

7*B@A

array([[  2023,    651,    623,  23947, -26523,  21021],
       [ -1393,  36876, 195279,   -525,   -602,   5306],
       [  4921,   1834,   8435,   1561,   1071,  -7259]])

In [ ]:
# b). Operación IA

I@A

array([[   3.,   -2.,    3.,   45.,   -8.,    0.],
       [   7.,    5.,   -1.,   97., -145.,  123.],
       [  -2.,   94.,  500.,    1.,    3.,    7.],
       [   8.,    2.,    8.,    1.,    2.,  -12.]])

In [ ]:
# c). Operación IC - CI

I@C - C@I

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# d). Operación (40C + 20I)A - 9A

(40*C + 20*I)@A - 9*A

array([[  1993.,   2058.,   -567.,  22575., -44808.,  38880.],
       [  1357.,  12455.,  60229.,  13187., -23635.,  20913.],
       [   898., -14406., -73900.,   8851.,  -2047.,  -1043.],
       [   128.,  15702.,  80448.,  -8709.,   2342.,   -452.]])

## **Transpuesta de una matriz**

### **Ejemplo 4:**
Crear las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
18 & -7 \\
4 & 9 \\
0 & 1
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
-5 & 0 & 0\\
4 & 1 & 1\\
-4 & 6 & 1
\end{pmatrix},
\end{equation*}

y realizar las operaciones indicadas:

a). $ A^{T}.$

b). $ B^{T}.$

c). $(3A)^{T}.$

In [ ]:
# Solución del Ejemplo 4.

# Creo las matrices A y B

A = np.array([[18, -7], [4, 9], [0, 1]])

B = np.array([[-5, 0, 0], [4, 1, 1], [-4, 6, 1]])

# Visualización de A y B

A, B

(array([[18, -7],
        [ 4,  9],
        [ 0,  1]]),
 array([[-5,  0,  0],
        [ 4,  1,  1],
        [-4,  6,  1]]))

In [ ]:
# a). Operación A^T

# Nota: La transpuesta de una matriz se puede ejecutar con el comando np.transpose

np.transpose(A)

array([[18,  4,  0],
       [-7,  9,  1]])

In [ ]:
# b). Operación B^T

np.transpose(B)

array([[-5,  4, -4],
       [ 0,  1,  6],
       [ 0,  1,  1]])

In [ ]:
# c). Operación (3A)^T

np.transpose(3*A)

array([[ 54,  12,   0],
       [-21,  27,   3]])


### **Ejemplo 5:**
Determine cuáles de las igualdades dadas a continuación son ciertas para las siguientes matrices:


\begin{equation*}
 A =
\begin{pmatrix}
4 & -7 & -1 & 3 \\
4 & 9 & 5 & 0 \\
1 & -1 & 6 & 10 \\
8 & 5 & -5 & 2
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
-5 & 3 & 4 & -4\\
-3 & 78 & 9 & -2\\
-4 & 6 & 1 & -3\\
2 & 4 & 0 & 12
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
3 & 1 & 1 & 1\\
0 & 0 & -4 & 2\\
0 & 2 & 3 & 3\\
2 & 7 & 1 & 2
\end{pmatrix}.
\end{equation*}

a). $ AB = BA.$

b). $ (A^{T})^T = A.$

c). $(AB)^{T} = A^T B^T.$

d). $(C+C^T)B^T = (BC^T)^T + (BC)^T$




In [3]:
# Solución del Ejemplo 5.

# Creo las matrices A, B y C

A = np.array([[4, -7, -1, 3], [4, 9, 5, 0], [1, -1, 6, 10],[8, 5, -5, 2]])

B = np.array([[-5, 3, 4, -4], [-3, 78, 9, -2], [-4, 6, 1, -3],[2, 4, 0, 12]])

C = np.array([[3, 1, 1, 1], [0, 0, -4, 2], [0, 2, 3, 3],[2, 7, 1, 2]])


In [4]:
# a). AB = BA

# Calculo AB

A@B


array([[  11, -528,  -48,   37],
       [ -67,  744,  102,  -49],
       [  -6,    1,    1,  100],
       [ -31,  392,   72,   -3]])

In [5]:
# a). AB = BA

# Calculo BA

B@A

array([[-36,  38,  64,  17],
       [293, 704, 457,  77],
       [-15,  66,  55,  -8],
       [120,  82, -42,  30]])

Observamos que el producto $AB$ es diferente de $BA$, por lo tanto, el producto de matrices no es conmutativa.

In [6]:
# b). (A^T)^T = A

# Calculo (A^T)^T

np.transpose(np.transpose(A))

array([[ 4, -7, -1,  3],
       [ 4,  9,  5,  0],
       [ 1, -1,  6, 10],
       [ 8,  5, -5,  2]])

Del cálculo anterior, podemos ver que la igualdad se satisface, es decir, que $(A^T)^T = A$. En efecto, dicha igualdad es válida para cualquier matriz.

In [7]:
# c). (AB)^T = (A^T)(B^T)

# Calculo (AB)^T

np.transpose(A@B)

array([[  11,  -67,   -6,  -31],
       [-528,  744,    1,  392],
       [ -48,  102,    1,   72],
       [  37,  -49,  100,   -3]])

In [8]:
# c). (AB)^T = (A^T)(B^T)

# Calculo (A^T)(B^T)

np.transpose(A)@np.transpose(B)

array([[-36, 293, -15, 120],
       [ 38, 704,  66,  82],
       [ 64, 457,  55, -42],
       [ 17,  77,  -8,  30]])

Los resultados indican que tal igualdad no es cierta para estas matrices. Por ello, tal igualdad no es válida.

In [9]:
# d). (C + C^T)(B^T) = (BC^T)^T + (BC)^T

# Calculo (C + C^T)(B^T)

(C + np.transpose(C))@np.transpose(B)


array([[ -35,   63,  -26,   52],
       [ -49,  -39,  -33,  110],
       [  -3, -113,  -22,   42],
       [  12,  721,   34,   90]])

In [11]:
# d). (C + C^T)(B^T) = (BC^T)^T + (BC)^T

# Calculo (BC^T)^T + (BC)^T

np.transpose(B@np.transpose(C)) + np.transpose(B@C)

array([[ -35,   63,  -26,   52],
       [ -49,  -39,  -33,  110],
       [  -3, -113,  -22,   42],
       [  12,  721,   34,   90]])

En consecuencia, la propiedad se satisface para dichas matrices. En general, esta propiedad es cierta para cualquier par de matrices.

# **Problemas de práctica**

**Ejercicio 1:** Defina las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
4 & -6 \\
-7 & 0
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
-5 & 2 \\
40 & -1 \\
0 & 4
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
3 & 8 \\
-5 & 5
\end{pmatrix}.
\end{equation*}

In [9]:
import numpy as np

# Creo las matrices A, B y C
A = np.array([[4, -6],[-7, 0]])
B = np.array([[2, -5],[40, -1],[0, 4]])
C = np.array([[3, 8],[-5, 5]])

# Visualización de A, B y C
A, B, C

(array([[ 4, -6],
        [-7,  0]]),
 array([[ 2, -5],
        [40, -1],
        [ 0,  4]]),
 array([[ 3,  8],
        [-5,  5]]))

**Ejercicio 2:** Usando las matrices anteriormente definidas, realice las operaciones indicadas:

a). $-6A + 3C^{T}.$

b). $ A + 2B.$ Debería obtener un error, explique la causa del error.

c). $(BC)^{T}$.

d). $CB$. Explique el resultado obtenido.

e). $AC$ y $CA$. ¿Coinciden los resultados?

f). $(A - C)^{T}$ y $A^T - C^T.$ ¿Coinciden los resultados?

g). $\|\vec{u}\|A + (\vec{u}\cdot \vec{v})C,$ donde $\vec{u} = (1, 0, 56)$ y $\vec{v} = (-30, 6, 8).$

h). $(\|-2\vec{u}\|A)C $ y $(\|\vec{u}\|A)(2C)$ donde $\vec{u} = (-9, 47, 206).$

In [27]:
# a). -6A+3C^T
print(-6*A + 3*np.transpose(C))

# b). A+2B
try:
    (A + 2*B)
    print(True)
except:
    print("La operación no se puede realizar porque la matriz A es de orden 2x2 y la matriz B es de orden 3x2")

# c). (BC)^T
print(np.transpose(B@C))

# d). CB
try:
    print(C@B)
    print("La matriz resultante es de orden 2x3")
except:
    print("La operación no se puede realizar porque el número de columnas de la matriz B es diferente al número de filas de la matriz C")

# e). AC = CA
print(A@C)
print(C@A)

if((A@C == C@A).all()):
    print(True)
else:
    print(False)

# f). (A-C))^T = A^T - C^T

print(np.transpose(A-C))
print(np.transpose(A) - np.transpose(C))

if((np.transpose(A-C) == np.transpose(A) - np.transpose(C)).all()):
    print(True)
else:
    print(False)

# g). ||u||A + (u*v)C, u = (1,0,56) v = (-30,6,8)

u = np.array([1,0,56])
v = np.array([-30,6,8])

print(np.linalg.norm(u)*A + (u@v)*C)

# h). (||-2u||A)C , (||u||A)(2C), u = (-9, 47, 206)

u = np.array([-9, 47, 206])

result1 = (np.linalg.norm(-2*u)*A)@C
result2 = (np.linalg.norm(u)*A)@(2*C)

print("------")
print(result1)
print(result2)

[[-15  21]
 [ 66  15]]
La operación no se puede realizar porque la matriz A es de orden 2x2 y la matriz B es de orden 3x2
[[ 31 125 -20]
 [ -9 315  20]]
La operación no se puede realizar porque el número de columnas de la matriz B es diferente al número de filas de la matriz C
[[ 42   2]
 [-21 -56]]
[[-44 -18]
 [-55  30]]
False
[[  1  -2]
 [-14  -5]]
[[  1  -2]
 [-14  -5]]
True
[[ 1478.03571144  3007.94643284]
 [-2482.06249502  2090.        ]]
------
[[ 17764.75882189    845.94089628]
 [ -8882.37941095 -23686.34509586]]
[[ 17764.75882189    845.94089628]
 [ -8882.37941095 -23686.34509586]]
